### PR TITLE
Fix label and unlabel command to throw CommandException for unwanted behaviour

### LINKED ISSUE #216: Label again overwrites existing label

### PR DESCRIPTION
**Pull request by ronniefun1**
Fixes #216

### CODE REVIEW

File: src/main/java/seedu/edubook/logic/commands/UnlabelCommand.java [hunk 1]
```diff
@@ -52,31 +52,71 @@ public CommandResult execute(Model model) throws CommandException {
...
+     * Processes label removal for each person in the list.
+     * <p>
+     * Skips students who already do not have a label and counts successes and skips.
+     *
+     * @param model The model to update.
+     * @param assignees The list of students to remove the label from.
+     * @return An array where index 0 is the number of successful assignment removals,
+     *         and index 1 is the number of skipped students.
+     */
+    private int[] processAssignments(Model model, List<Person> assignees) {
```
Comment (williamoose) [inline src/main/java/seedu/edubook/logic/commands/UnlabelCommand.java]: Similarly here should be processLabels
